apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-mongos1
  namespace: mongodb-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-mongos1
  template:
    metadata:
      labels:
        app: mongo-mongos1
    spec:
      containers:
      - name: mongo
        image: mongo:6.0
        command:
        - mongos
        - --configdb
        - configReplSet/mongo-config-0.mongo-config.mongodb-cluster.svc.cluster.local:27019,mongo-config-1.mongo-config.mongodb-cluster.svc.cluster.local:27019,mongo-config-2.mongo-config.mongodb-cluster.svc.cluster.local:27019
        - --bind_ip_all
        - --port
        - "27017"
        ports:
        - containerPort: 27017
          name: mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-mongos2
  namespace: mongodb-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-mongos2
  template:
    metadata:
      labels:
        app: mongo-mongos2
    spec:
      containers:
      - name: mongo
        image: mongo:6.0
        command:
        - mongos
        - --configdb
        - configReplSet/mongo-config-0.mongo-config.mongodb-cluster.svc.cluster.local:27019,mongo-config-1.mongo-config.mongodb-cluster.svc.cluster.local:27019,mongo-config-2.mongo-config.mongodb-cluster.svc.cluster.local:27019
        - --bind_ip_all
        - --port
        - "27017"
        ports:
        - containerPort: 27017
          name: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-mongos
  namespace: mongodb-cluster
  labels:
    app: mongo-mongos
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo-mongos1  # Load balance between the two